@uri=http://localhost:8081

GET {{uri}}/.well-known/openid-configuration HTTP/1.1

###
GET {{uri}}/.well-known/jwks.json HTTP/1.1

###
GET {{uri}}/test HTTP/1.1

###
POST {{uri}}/clients HTTP/1.1
Content-Type: application/json

{
    "client_name": "TestClient",
    "redirect_uris": ["http://localhost/callback"],
    "grant_types": ["authorization_code"],
    "response_types": ["code"],
    "client_type": "confidential",
    "scopes": ["openid", "profile", "email"]
}

###
GET {{uri}}/clients/cd4e7670-5e96-4a3f-addb-51fa43db86fc HTTP/1.1

### http://localhost:8081/oauth/authorize?response_type=code&client_id=1e95c08f-d409-446c-be32-c7d1f1930120&redirect_uri=http://localhost/callback&scope=openid%20profile&state=xyz

POST {{uri}}/oauth/token HTTP/1.1
Content-Type: application/json

{
    "client_id": "1e95c08f-d409-446c-be32-c7d1f1930120",
    "state": "xyz",
    "client_secret": "XxuvgtF4UjQgR7I4RgIBJS0RC6WkCVIdRN_W8MzY7kk",
    "code": "QWkKCFTD2a06df89-aceb-4b6d-8d0f-133ff85c99a9",
    "grant_type": "authorization_code",
    "redirect_uri": "http://localhost/callback"
}

###
POST {{uri}}/oauth/token HTTP/1.1
Content-Type: application/json

{
    "client_id": "1e95c08f-d409-446c-be32-c7d1f1930120",
    "state": "xyz",
    "client_secret": "XxuvgtF4UjQgR7I4RgIBJS0RC6WkCVIdRN_W8MzY7kk",
    "code": "eyJhbGciOiJSUzI1NiIsImtpZCI6IlJTMjU2LVFMYlBic0RfaTVrIiwidHlwIjoiSldUIn0.eyJhdWQiOiIxZTk1YzA4Zi1kNDA5LTQ0NmMtYmUzMi1jN2QxZjE5MzAxMjAiLCJjbGllbnRfaWQiOiIxZTk1YzA4Zi1kNDA5LTQ0NmMtYmUzMi1jN2QxZjE5MzAxMjAiLCJleHAiOjE3NjgyMjc5MTQsImlhdCI6MTc2ODE0MTUxNCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIiwianRpIjoiMTVlNzMxMTgtYWNmMC00NTBhLTkzNjQtNDU4OTM4YzljOGUxMmEwNmRmODktYWNlYi00YjZkLThkMGYtMTMzZmY4NWM5OWE5Iiwic2NvcGUiOiIiLCJzdWIiOiJ0b2tlbl9hdXRoZW50aWNhdGlvbl9jb2RlIn0.n0mPcTi9ctKQ-Z2uIgN4cYrQXS0k76tqDT-GgCKZtP6araQTT_OWJ37VJYVrastHsPX8Xg4e_epnXfwYRLv3bfql_o5THc-E0Wwo2VwUbRpAp-IDWecggy4m8KE5v_cQqIb8Vf-11kRWeIwPYH1n_kPRXEqsnWElCQSmkxJzDjS1CH6ul4FhBsbFPpd6ecOGh3UkXGtp5YDB37PQaFxDuVgMjxU5Un56grVmT4LQ9TrtODy4qTKFgabUtkPoHV05roWRhtF7gnwxTZXmd0rscRTXEV7CMl7mp8IqwbpTnPjgzw5ZvQbjyqP-dS0kzBsLl0u-twabUGUzZtij_A8GQA",
    "grant_type": "refresh_token",
    "redirect_uri": "http://localhost/callback"
}