@uri=http://localhost:8081

GET {{uri}}/.well-known/openid-configuration HTTP/1.1

###
GET {{uri}}/.well-known/jwks.json HTTP/1.1

###
GET {{uri}}/test HTTP/1.1

###
POST {{uri}}/clients HTTP/1.1
Content-Type: application/json

{
    "client_name": "TestClient",
    "redirect_uris": ["http://localhost/callback"],
    "grant_types": ["authorization_code"],
    "response_types": ["code"],
    "client_type": "confidential",
    "scopes": ["openid", "profile", "email"]
}

###
GET {{uri}}/clients/cd4e7670-5e96-4a3f-addb-51fa43db86fc HTTP/1.1

### http://localhost:8081/oauth/authorize?response_type=code&client_id=1e95c08f-d409-446c-be32-c7d1f1930120&redirect_uri=http://localhost/callback&scope=openid%20profile&state=xyz

POST {{uri}}/oauth/token HTTP/1.1
Content-Type: application/json

{
    "client_id": "1e95c08f-d409-446c-be32-c7d1f1930120",
    "state": "xyz",
    "client_secret": "XxuvgtF4UjQgR7I4RgIBJS0RC6WkCVIdRN_W8MzY7kk",
    "code": "f8zI1gbc1103f581-b24c-4610-847f-59ed5a13b8dc",
    "grant_type": "authorization_code",
    "redirect_uri": "http://localhost/callback"
}

###
POST {{uri}}/oauth/token HTTP/1.1
Content-Type: application/json

{
    "client_id": "1e95c08f-d409-446c-be32-c7d1f1930120",
    "state": "xyz",
    "client_secret": "XxuvgtF4UjQgR7I4RgIBJS0RC6WkCVIdRN_W8MzY7kk",
    "code": "eyJhbGciOiJSUzI1NiIsImtpZCI6IlJTMjU2LVFMYlBic0RfaTVrIiwidHlwIjoiSldUIn0.eyJhdWQiOiIxZTk1YzA4Zi1kNDA5LTQ0NmMtYmUzMi1jN2QxZjE5MzAxMjAiLCJjbGllbnRfaWQiOiIxZTk1YzA4Zi1kNDA5LTQ0NmMtYmUzMi1jN2QxZjE5MzAxMjAiLCJleHAiOjE3NjgyMzEwMjgsImlhdCI6MTc2ODE0NDYyOCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxIiwianRpIjoiZDAwMzU4YWYtN2IyYS00ODQzLWIyOWQtYzZiMTNiNGI4ODhjMTEwM2Y1ODEtYjI0Yy00NjEwLTg0N2YtNTllZDVhMTNiOGRjIiwic2NvcGUiOiIiLCJzdWIiOiJ0b2tlbl9hdXRoZW50aWNhdGlvbl9jb2RlIn0.dGFirz1j6UQoGDgaBhqRpg6IlLJSFPv3BhO1v4V9egiKuYlLAd5LRctI3lNVvnBvmRq3J3qSB6KhGL97sFaZ35DbFnBXlnM9WlZqgnourh35sULjLRp9DiA_1EHxuQkkmz1qEM0FchtTuwkhzPwYXR1ehFjjseHOWq39WdfiDKlCPAPV7T5tP0CO561no4Ym83mDThaJM-d2_njtfLYoyollHLCsadpU3mf-y-JPPI6RZJivzdfSKwekITugdqUoNAUjhrsQ-PBmNdUyGSR09ANdEzYZzXUDjK8M_jA-hC7ykPM_RT2yHb_qphZ86l2GLFpiWGN-gt_ZXIZk5b7SVg",
    "grant_type": "refresh_token",
    "redirect_uri": "http://localhost/callback"
}